/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package clock.controller;

import java.util.Date;
import javax.swing.JComponent;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author joshualange
 */
public class TimeControl extends javax.swing.JPanel {
    SpinnerDateModel dateModel;
    JComponent dateEditor;
    /**
     * Creates new form TimeControl
     */
    public TimeControl() {
        initComponents();
        dateModel = new SpinnerDateModel();

        timeSelection.setModel(dateModel);
        dateEditor = new JSpinner.DateEditor(timeSelection, "h:mm a");
        timeSelection.setEditor(dateEditor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timeSelection = new javax.swing.JSpinner();
        enabledCheck = new javax.swing.JCheckBox();

        timeSelection.setEnabled(false);

        enabledCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enabledCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enabledCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enabledCheck))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enabledCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enabledCheckActionPerformed
        timeSelection.setEnabled(enabledCheck.isSelected());
    }//GEN-LAST:event_enabledCheckActionPerformed

public Date getTime(){
    if (dateEditor!=null) {
        return dateModel.getDate();
    }
    return null;
}
public void setTime(Date time){
    if (dateEditor!=null) {
        dateModel.setValue(time);
    }
}
public boolean getEnabled(){
    return enabledCheck.isSelected();
}

    @Override
    public void setEnabled(boolean enabled){
    enabledCheck.setSelected(enabled);
    timeSelection.setEnabled(enabled);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox enabledCheck;
    private javax.swing.JSpinner timeSelection;
    // End of variables declaration//GEN-END:variables
}
